# File: src/Gemfile
# 
# By: Daniel Morales <daniminas@gmail.com>
#
# Web: https://github.com/danielm/vagrant-ruby
#
# Licence: GPL/MIT

source 'https://rubygems.org'

# SinatraRB Framework
gem "sinatra"


# With this we are going to requiere tux only on development mode.
# tux is a tool that allows you to interact with your Sinatra app from a command line
group :development do
 gem "tux"
end

